name: Build Windows Release Package

on:
  pull_request:
  push:
    tags:
      - 'build*' # Push events to matching build* tags
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==6.4.0

    - name: Build Executable
      run: |
        pyinstaller build_win_pkg.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: semi-utils-exe
        path: dist/semi-utils.exe
